### PR TITLE
Use psycopg2 over psycopg2-binary for FIPS compliance in fedramp

### PR DESCRIPTION
**Pull request by TGPSKI**
This MR removes psycopg2-binary and replaces it with a FIPS-compliant version, psycopg2.

### CODE REVIEW

**Comment by TGPSKI** [comment]
```00:49:59      command: /opt/app-root/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/dashdotdb/setup.py'"'"'; __file__='"'"'/dashdotdb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-q1e0w04m/install-record.txt --single-version-externally-managed --compile --install-headers /opt/app-root/include/site/python3.9/dashdotdb
00:49:59          cwd: /dashdotdb/
00:49:59     Complete output (5 lines):
00:49:59     running install
00:49:59     running build
00:49:59     running build_py
00:49:59     creating build
00:49:59     error: could not create 'build': Permission denied
00:49:59     ----------------------------------------
```

**Comment by TGPSKI** [comment]
Not stale!

**Comment by fishi0x01** [comment]
LGTM from my side. Needs a rebase because we do not use `latest` Dockerimage anylonger here.

**Review by fishi0x01 — APPROVED** [review]

**Comment by hemslo** [comment]
A simplified version of Dockerfile can be like this
```dockerfile
FROM registry.access.redhat.com/ubi8/python-39:latest AS builder
USER 0
RUN dnf upgrade -y && dnf install -y \
    libpq-devel \
    python3-devel
USER 1001
RUN python -m venv venv
ENV PATH="$HOME/venv/bin:$PATH"
COPY . .
RUN pip3 install --no-cache-dir .

FROM registry.access.redhat.com/ubi8/python-39:latest
COPY --from=builder $HOME/venv ./venv
COPY . .
ENV PATH="$HOME/venv/bin:$PATH"
ENTRYPOINT ["./entrypoint.sh"]
```

Some further improvements can be
* generate and checkin requirements.txt file, so we don't need to copy all files before pip install
* merge ci dockerfile together using multistage build
* update `.dockerignore` to include `.git` and all entries from `.gitignore`

And due to some pacakges update, I have to pin several more versions in `setup.py` to run it locally now
```
            # Newer versions are not compatible with our Flask version
            'SQLAlchemy == 1.4.46',
            'itsdangerous == 1.1.0',
            'markupsafe == 2.0.1',
            'werkzeug == 1.0.1',
```

**Pull request closed without merging**
